type: pipeline_definition
product: Liberty
name: Open Liberty Delivery Requirements Verification
description: "Examines Open Liberty code changes for delivery standards compliance"
triggers:
- type: manual
  description: "Runs CI Orchestrator-managed Jenkins jobs to examine pull request changes and create required status checks"
  triggerName: "libby"
  triggerRank: 50
  groups: ["LibertyDev"]
  propertyDefinitions:
    - name: githubPRNumber
      required: true
      description: "PR number to perform delivery requirement verification against e.g. 30188"

steps:
- stepName: PR Changes
  workType: PRChangesDetection
  timeoutInMinutes: 30
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
- stepName: Copyright Header Check
  workType: Jenkins
  projectName: copyrightHeaderCheck
  timeoutInMinutes: 120
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"  
- stepName: Prohibited Terms Check
  workType: Jenkins
  projectName: prohibitedTermsCheck
  timeoutInMinutes: 120
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
- stepName: Code Checklist Creation
  workType: Jenkins
  projectName: codeCheckListBuilder
  timeoutInMinutes: 120
  dependsOn:
  - stepName: PR Changes
    awaitOutputProperties: true
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
    isBvtCodeChanged: ${PR Changes:is.bvt.code.changed}
    isFatCodeChanged: ${PR Changes:is.fat.code.changed}
    isInfraCodeChanged: ${PR Changes:is.infra.code.changed}
    isProductCodeChanged: ${PR Changes:is.product.code.changed}
    isTestInfraCodeChanged: ${PR Changes:is.test.infra.code.changed}
    isUnittestCodeChanged: ${PR Changes:is.unittest.code.changed}    
    bvtFilesCount: ${PR Changes:bvt.files.count}
    fatFilesCount: ${PR Changes:fat.files.count}
    infraFilesCount: ${PR Changes:infra.files.count}
    productFilesCount: ${PR Changes:product.files.count}
    testInfraFilesCount: ${PR Changes:test.infra.files.count}
    unittestFilesCount: ${PR Changes:unittest.files.count}
