receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector-metrics:4317
      http:
        endpoint: otel-collector-metrics:4318

exporters:
  prometheus:
    endpoint: otel-collector-metrics:8889
  debug:
    verbosity: basic

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

  telemetry:
    logs:
      level: debug